config/routes.rb
Rails.application.routes.draw do

	namespace :admin do
		resources :users
		resources :sessions
		resources :albums
		resources :settings
		resources :faqs
		root 'settings#index'

		get 'login' => 'sessions#new', as: :login
		post 'logout' => 'sessions#destroy', as: :logout
	end

	get 'faq', to: 'pages#faq'
	root to: 'pages#home'  
end

app/models/album.rb
class Album < ApplicationRecord
	mount_uploaders :photos, PhotoUploader
	default_scope { order(created_at: :asc) }

	def created_at_f
		created_at.strftime('%d/%m/%Y')
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faq.rb
class Faq < ApplicationRecord
	default_scope { order(created_at: :asc) }
end

app/models/setting.rb
class Setting < ApplicationRecord
	mount_uploader :home_photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController
	before_action :set_album, only: [:show, :edit, :update, :destroy]

	def index
		@albums = Album.all
	end

	def show
	end

	def new
		@album = Album.new
	end

	def create
		@album = Album.new(album_params)
		if @album.save
			redirect_to admin_album_path(@album), notice: 'Album creado.'
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @album.update_attributes(album_params)
			redirect_to admin_album_path(@album), notice: 'Album actualizado.'
		else
			render :edit
		end
	end

	def destroy
		@album.destroy
		redirect_to admin_albums_path, notice: 'Album eliminado.'
	end

	private

		def set_album
			@album = Album.find(params[:id])
		end

		def album_params
			params.require(:album).permit(:name, :description, {photos: []})
		end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

	layout 'admin'
	before_action :require_login

	private

		def not_authenticated
			redirect_to admin_login_path, alert: 'Debes iniciar sesión primero.'
		end

end

app/controllers/admin/faqs_controller.rb
class Admin::FaqsController < Admin::BaseController
	before_action :set_faq, only: [:update, :destroy]

	def index
		@faqs = Faq.all
	end

	def create
		@faq = Faq.new(faq_params)
		if @faq.save
			redirect_to admin_faqs_path, notice: 'Pregunta agregada.'
		else
			redirect_to admin_faqs_path, alert: 'Hubo un error. Intente de nuevo.'
		end
	end

	def update
		if @faq.update_attributes(faq_params)
			redirect_to admin_faqs_path, notice: 'Pregunta actualizada.'
		else
			redirect_to admin_faqs_path, alert: 'Hubo un error. Intente de nuevo.'
		end
	end

	def destroy
		@faq.destroy
		redirect_to admin_faqs_path, notice: 'Pregunta eliminada.'
	end

	private

		def set_faq
			@faq = Faq.find(params[:id])
		end

		def faq_params
			params.require(:faq).permit!
		end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController
	skip_before_action :require_login, except: [:destroy]

	def index
		redirect_to new_admin_session_path
	end

	def new
		@admin = User.new
	end

	def create
		if @admin = login(params[:email], params[:password])
			redirect_back_or_to(admin_root_path)
		else
			flash.now[:alert] = 'El login falló. Intente de nuevo.'
			render action: 'new'
		end
	end

	def destroy
		logout
		redirect_to root_path, notice: 'Sesión cerrada!'
	end

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController

	def index
		@settings = Setting.first_or_create do |setting|
			setting.home_text = 'Tienes que llenarme en el panel de administración!'
			setting.address = 'Igual a mi'
			setting.telephone = 'Igual a mi'
		end
	end

	def update
		@settings = Setting.find(params[:id])
		if @settings.update_attributes(settings_params)
			redirect_to admin_settings_path, notice: 'Actualización exitosa!'
		else
			render :index
		end
	end

	private

		def settings_params
			params.require(:setting).permit!
		end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'El administrador ha sido registrado.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'Los datos fueron actualizados.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: 'El administrador fue eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@settings = Setting.first
		@albums = Album.all
	end

	def faq
		@settings = Setting.first
		@faqs = Faq.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/albums/_form.html.erb
<%= form_for([:admin, album]) do |f| %>
  <% if album.errors.any? %>
    <div id="error_explanation" class="notification is-danger">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nombre', class: 'label' %>
    <div class="control">
      <%= f.text_field :name, class: 'input' %>
    </div>
  </div>

  <div class="field">
   <%= f.label :description, 'Descripción (opcional)', class: 'label' %>
   <div class="control">
     <%= f.text_area :description, class: 'input' %>
   </div>
  </div>
  
  <div class="field">
     <%= f.label :photos, 'Agregar las fotos', class: 'label' %>
     <div class="control">
       <%= f.file_field :photos, multiple: true %>
     </div>
  </div>

  <div class="actions">
    <%= f.submit 'Guardar', class: 'button is-primary' %>
  </div>
<% end %>

app/views/admin/albums/edit.html.erb
<h1 class="is-size-4">Editar este album</h1>

<br>

<%= render 'admin/albums/form', album: @album %>

<hr>

<%= link_to 'Cancelar', admin_albums_path %>

app/views/admin/albums/index.html.erb
<h1 class="is-size-3">Listado de albumes</h1>

<br>

<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Fecha de creación</th>
        <th>Número de fotos</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @albums.each do |album| %>
        <tr>
          <td><%= album.name %></td>
          <td><%= album.description %></td>
          <td><%= album.created_at %></td>
          <td><%= album.photos.count %></td>
          <td><%= link_to 'Ver', admin_album_path(album) %></td>
          <td><%= link_to 'Editar', edit_admin_album_path(album) %></td>
          <td><%= link_to 'Eliminar', admin_album_path(album), method: :delete, data: { confirm: 'Estás seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Agregar album nuevo', new_admin_album_path, class: 'button is-primary' %>

app/views/admin/albums/new.html.erb
<h1 class="is-size-4">Agregar nuevo album</h1>

<br>

<div class="columns">
	<div class="column">
		<%= render 'admin/albums/form', album: @album %>
	</div>
	<div class="column"></div>
</div>

<hr>

<%= link_to 'Cancelar', admin_albums_path %>

app/views/admin/albums/show.html.erb
<h1 class="is-size-4"><%= @album.name %></h1>

<p>Creado el: <b><%= @album.created_at_f %></b></p>
<p><%= @album.description %></p>
<br>
<p>
	<%= link_to 'Editar', edit_admin_album_path(@album), class: 'button is-warning' %>
	<%= link_to 'Eliminar', admin_album_path(@album), method: :delete, data: { confirm: 'Estás seguro?' }, class: 'button is-danger' %>
</p>

<hr>

<div class="photos columns is-multiline">
	<% @album.photos.each do |photo| %>
		<div class="photo column is-one-quarter">
			<%= image_tag photo.thumb %>
		</div>
	<% end %>
</div>

app/views/admin/faqs/_form.html.erb
<%= form_for([:admin, faq]) do |f| %>

	<div class="field">
		<label class="label">Pregunta</label>
		<div class="control">
			<%= f.text_area :question, class: 'textarea', rows: '1' %>
		</div>
	</div>

	<div class="field">
		<label class="label">Respuesta</label>
		<div class="control">
			<%= f.text_area :answer, class: 'textarea' %>
		</div>
	</div>

	<div class="field">
		<%= f.submit 'Guardar', class: 'button is-primary is-small' %>

		<% if !faq.question.blank? %>
			<%= link_to 'Eliminar', admin_faq_path(faq), method: :delete, class: 'button is-danger is-small', data: { confirm: 'Estás seguro?' } %>
		<% end %>
	</div>

<% end %>

app/views/admin/faqs/index.html.erb
<h1 class="is-size-4">Preguntas frecuentes</h1>

<br>

<div class="columns">
	<div class="column">
		<p>Listado de preguntas</p>
		<br>
		<% if @faqs.count == 0 %>
			<div class="notification is-default">
				No tienes ninguna pregunta/respuesta, agrega unas cuantas...
			</div>
		<% end %>
		<% @faqs.each do |faq| %>
			<%= render 'admin/faqs/form', faq: faq %>
			<hr>
		<% end %>
	</div>
	<div class="column">
		<p>Agrega una pregunta/respuesta nueva</p>
		<br>

		<%= render 'admin/faqs/form', faq: Faq.new %>	
	</div>
</div>

app/views/admin/settings/index.html.erb
<h1 class="is-size-4">Configuración</h1>

<br>

<div class="settings columns">
	<div class="column">
		<%= form_for([:admin, @settings]) do |f| %>
			<div class="field">
				<label class="label">Foto de inicio</label>
				<%= image_tag @settings.home_photo if @settings.home_photo? %>
				<%= f.file_field :home_photo %>
				<%= f.hidden_field :home_photo_cache %>
			</div>
			<div class="field">
				<div class="control">
					<label class="label">Texto "Nosotros"</label>
					<%= f.text_area :home_text, class: 'textarea', rows: '10' %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<label class="label">Domicilio</label>
					<%= f.text_field :address, class: 'input' %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<label class="label">Teléfono</label>
					<%= f.text_field :telephone, class: 'input' %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<label class="label">Página de instagram</label>
					<%= f.text_field :instagram, class: 'input' %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<label class="label">Página de facebook</label>
					<%= f.text_field :facebook, class: 'input' %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<label class="label">Página de V?</label>
					<%= f.text_field :vsite, class: 'input' %>
				</div>
			</div>
			<div class="field">
				<%= f.submit 'Guardar', class: 'button is-primary' %>
			</div>
		<% end %>
	</div>
	<div class="column"></div>
</div>

app/views/admin/users/_form.html.erb
<%= form_for([:admin, user]) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="notification is-danger">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, 'Correo', class: 'label' %>
    <div class="control">
      <%= f.text_field :email, id: :user_email, class: 'input' %>
    </div>
  </div>

  <div class="field">
   <%= f.label :password, 'Contraseña', class: 'label' %>
   <div class="control">
     <%= f.password_field :password, class: 'input' %>
   </div>
  </div>
  
  <div class="field">
     <%= f.label :password_confirmation, 'Confirmación de contraseña', class: 'label' %>
     <div class="control">
       <%= f.password_field :password_confirmation, class: 'input' %>
     </div>
  </div>

  <div class="actions">
    <%= f.submit 'Guardar', class: 'button is-primary' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<br>

<%= render 'form', user: @user %>

<hr>

<%= link_to 'Cancelar', admin_users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="is-size-4">Administradores</h1>

<br>

<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Correo</th>
        <th>Fecha registro</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.created_at %></td>
          <td><%= link_to 'Editar', edit_admin_user_path(user) %></td>
          <td><%= link_to 'Eliminar', admin_user_path(user), method: :delete, data: { confirm: 'Estás seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Admin nuevo', new_admin_user_path, class: 'button is-primary' %>

app/views/admin/users/new.html.erb
<h1 class="is-size-4">Administrador nuevo</h1>

<br>

<div class="columns">
	<div class="column">
		<%= render 'form', user: @user %>
	</div>
	<div class="column"></div>
</div>

<hr>
<%= link_to 'Cancelar', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/layouts/_admin_nav.html.erb
<nav class="navbar">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <b>Venazul.mx</b>
    </a>
    <div class="navbar-burger burger" data-target="navMenu">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navMenu" class="navbar-menu">
    <% if current_user %>
      <div class="navbar-start">
        <%= link_to 'Configuración', admin_root_path, class: 'navbar-item' %>
        <%= link_to 'Albumes', admin_albums_path, class: 'navbar-item' %>
        <%= link_to 'Preguntas Frecuentes', admin_faqs_path, class: 'navbar-item' %>
        <%= link_to 'Administradores', admin_users_path, class: 'navbar-item' %>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <b><%= current_user.email %></b>
        </div>
        <%= link_to "Salir", admin_logout_path, method: :post, class: 'navbar-item' %>
      </div>
    <% end %>
  </div>
</nav>

<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {

  $(document).on('click', '.navbar-burger', function (e) {
    var target = $(this).data('target');
    var $target = $('#' + target);
    $(this).toggleClass('is-active');
    $target.toggleClass('is-active');
  });

});
</script>

app/views/layouts/_footer.html.erb
<footer id="contacto">
	<h2>Contacto</h2>
	<hr>
	<div class="info">
		<%= @settings.address %>
		<span>Tel. <%= @settings.telephone %></span>
	</div>
	<div class="social">
		<ul>
			<li><a href="<%= @settings.instagram %>"><%= image_tag 'insta.png', alt: 'insta' %></a></li>
			<li><a href="<%= @settings.facebook %>"><%= image_tag 'fb.png', alt: 'fb' %></a></li>
			<li><a href="<%= @settings.vsite %>"><%= image_tag 'vs.png', alt: 'vsite' %></a></li>
		</ul>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="header">
	<div class="top">
		<div class="logo">
			<a href="/"><%= image_tag 'logo.png', alt: 'Venazul' %></a>
		</div>
	</div>

	<nav class="nav">
		<div class="item">
			<%= link_to 'Nosotros', '/#nosotros' %>		
		</div>
		<div class="item">
			<%= link_to 'Portafolio', '/#portafolio' %>
		</div>
		<div class="item">
			<%= link_to 'Preguntas Frecuentes', faq_path %>
		</div>
		<div class="item">
			<%= link_to 'Contacto', '/#contacto' %>
		</div>
	</nav>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venazul - ADMIN</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'bulma', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container is-fluid">
      <%= render 'layouts/admin_nav' %>
    </div>
    <div class="container">
      <% if flash[:notice] %>
        <br>
        <p class="notification is-warning" id="notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert] %>
        <br>
        <p class="notification is-danger" id="alert"><%= flash[:alert] %></p>
      <% end %>

      <div class="section">
        <%= yield %>
      </div>
    </div>
    <br>
    <br>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venazul</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_portfolio.html.erb
<div class="portfolio" id="portafolio">
	<h2>Portafolio</h2>
	<div class="albums">
		<% @albums.each do |album| %>
			<div class="album" data-name="<%= album.name %>" data-gallery="<%= 'gallery-' + album.id.to_s %>">
				<div class="overlay">
					<span><%= album.name %></span>
				</div>
				<%= image_tag album.photos.first.thumb %>
				<input
					type="hidden"
					id="<%= 'gallery-' + album.id.to_s %>"
					value="<%= album.photos.to_json %>">
			</div>
		<% end %>		
	</div>
</div>

<script type="text/javascript">
	
	$(document).ready(function() {
		$('.album').on('click', function() {
			var name = $(this).data('name')
			var gallery_id = $(this).data('gallery');
			var data = $('#' + gallery_id).val();
      data = JSON.parse(data);

			var gallery = [];
			data.forEach(function(image) {
				gallery.push({
					href: image.view.url,
					title: name
				})
      });
			$.swipebox(gallery);
		});
	});

</script>

app/views/pages/faq.html.erb
<div class="faqs">
	<h2>Preguntas frecuentes</h2>

	<% @faqs.each do |faq| %>
		<ul>
			<li>
				<div class="question">
					<%= faq.question %>
				</div>
				<div class="answer">
					<%= faq.answer %>
				</div>
			</li>
		</ul>
	<% end %>	
</div>

app/views/pages/home.html.erb
<div class="welcome">
	<%= image_tag @settings.home_photo %>
</div>

<div class="about" id="nosotros">
	<h2>Nosotros</h2>
	<p><%= @settings.home_text %></p>
</div>

<%= render 'pages/portfolio' %>